[package]
name = "simu"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pub"
path = "src/pub.rs"

[[bin]]
name = "sub"
path = "src/sub.rs"


[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
redis = "0.27.5"
rqlite = "0.1.0"
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }
zenoh = "1.0.2"
