version: '3.8'

services:

  zenoh:
    image: eclipse/zenoh
    container_name: zenoh
    ports:
      - "7447:7447"
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./zenoh_docker:/root/.zenoh

  otel_lgtm:
    image: grafana/otel-lgtm:latest
    container_name: otel
    ports:
      - "3000:3000"
      - "4318:4318"
      - "4317:4317"
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554"
      - "1935:1935"
      - "8888:8888"
      - "8889:8889"
      - "8890:8890/udp"
      - "8189:8189/udp"
    environment:
      - MTX_WEBRTCADDITIONALHOSTS=0.0.0.0
      - MTX_RTSPTRANSPORTS=tcp
    restart: unless-stopped

    # DOCS:
    #   - ffmpeg -f v4l2 -i /dev/video0 -c:v libx264 -pix_fmt yuv420p -preset ultrafast -tune zerolatency -b:v 200k -f rtsp rtsp://0.0.0.0:8554/tester
    #   - ffplay -fflags nobuffer -fflags discardcorrupt -flags low_delay -framedrop -avioflags direct -rtsp_transport  tcp rtsp://localhost:8554/tester
    #
    # INTERNET:
    #   - ffmpeg -f v4l2 -i /dev/video0 -c:v libx264 -preset ultrafast -tune zerolatency -b:v 200k -maxrate 1M -bufsize 2M -f rtsp rtsp://localhost:8554/tester
    #   - ffplay rtsp://localhost:8554/tester -fflags nobuffer -flags low_delay -strict experimental
    #   - gst-launch-1.0 rtspsrc location=rtsp://localhost:8554/tester latency=0 ! decodebin ! videoconvert ! autovideosink

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   container_name: jaeger
  #   environment:
  #     - COLLECTOR_ZIPKIN_HOST_PORT=:9411
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - "6831:6831/udp"
  #     - "6832:6832/udp" 
  #     - "5778:5778" 
  #     - "16686:16686" 
  #     - "4317:4317" 
  #     - "4318:4318" 
  #     - "14250:14250" 
  #     - "14268:14268" 
  #     - "14269:14269" 
  #     - "9411:9411" 
  #   restart: unless-stopped

volumes:
  data:


