version: '3.8'

services:

  zenoh:
    image: eclipse/zenoh
    container_name: zenoh
    ports:
      - "7447:7447"
      - "8000:8000"
    restart: unless-stopped

  valkey:
    image: valkey/valkey
    container_name: valkey
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: valkey-server --appendonly yes
    restart: unless-stopped

volumes:
  data:


