version: '3.8'

services:

  zenoh:
    image: eclipse/zenoh
    container_name: zenoh
    ports:
      - "7447:7447"
      - "8000:8000"
    restart: unless-stopped

  otel_lgtm:
    image: grafana/otel-lgtm:latest
    container_name: otel
    ports:
      - "3000:3000"
      - "4318:4318"
      - "4317:4317"
    restart: unless-stopped

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   container_name: jaeger
  #   environment:
  #     - COLLECTOR_ZIPKIN_HOST_PORT=:9411
  #     - COLLECTOR_OTLP_ENABLED=true
  #   ports:
  #     - "6831:6831/udp"
  #     - "6832:6832/udp" 
  #     - "5778:5778" 
  #     - "16686:16686" 
  #     - "4317:4317" 
  #     - "4318:4318" 
  #     - "14250:14250" 
  #     - "14268:14268" 
  #     - "14269:14269" 
  #     - "9411:9411" 
  #   restart: unless-stopped

volumes:
  data:


